---
# This file configures https://pre-commit.com/
# to use specific hooks and options.
fail_fast: true

repos:
  - repo: local
      - id: clang-format
        name: clang-format
        entry: hooks/clang-format
        description: Formats C/CPP code
        args: [-i, -style=Google]
        types: [c, c++]
        language: script
      - id: clang-tidy
        name: clang-tidy
        entry: hooks/clang-tidy
        description: Find warnings/errors in C/CPP code
        args: [-fix-errors, -quiet, -checks=*, -warnings-as-errors=*]
        types: [c, c++]
        language: script
      - id: oclint
        name: oclint
        entry: hooks/oclint
        description: Find warnings/errors in C/CPP code
        args: [-enable-global-analysis, -enable-clang-static-analyzer]
        types: [c, c++]
        language: script
