---
# This file configures https://pre-commit.com/
# to use specific hooks and options.
fail_fast: true

repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: master
    hooks: 
      - id: shellcheck
        args: ["--color=always", "--shell=bash", "-x", "-a"]
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: hooks/clang-format
        description: Formats C/CPP code
        types: [c, c++]
        language: script
        additional_dependencies: [clang-format]
      - id: clang-tidy
        name: clang-tidy
        entry: hooks/clang-tidy
        description: Find warnings/errors in C/CPP code
        types: [c, c++]
        language: script
        additional_dependencies: [clang-tidy]
      - id: oclint
        name: oclint
        entry: hooks/oclint
        description: Find warnings/errors in C/CPP code
        types: [c, c++]
        language: script
        additional_dependencies: [oclint]

